/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_morajixon;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL-INS14
 */
public class Horario extends javax.swing.JFrame {
    Conexion c=new Conexion();
    Connection con=c.conectar();
    /**
     * Creates new form Horario
     */
    public Horario() {
        initComponents();
        MostrarEmpl();
        MostrarPuesto();
        setIconImage(new ImageIcon(getClass().getResource("/Image/guardia.png")).getImage());//Agrega icono al aplicativo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Dtm_Fecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        Txt_Apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Txt_Cedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_Puesto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Txt_Delta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Txt_CodPuesto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Txa_Obs = new javax.swing.JTextArea();
        Cmb_Actividad = new javax.swing.JComboBox<>();
        Cmb_Jornada = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Principal = new javax.swing.JTable();
        Dtm_Desde = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Dtm_Hasta = new com.toedter.calendar.JDateChooser();
        Btn_Buscar = new javax.swing.JButton();
        Btn_Atras1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Btn_Limpiar = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_Actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Empleado = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Puesto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HORARIO");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Fecha:");

        jLabel3.setText("Nombre :");

        Txt_Nombre.setEnabled(false);

        Txt_Apellido.setEnabled(false);

        jLabel5.setText("Actividad :");

        jLabel6.setText("Jornada :");

        jLabel7.setText("Observacion :");

        jLabel13.setText("Cedula :");

        Txt_Cedula.setBackground(new java.awt.Color(240, 240, 240));
        Txt_Cedula.setEnabled(false);

        jLabel4.setText("Puesto :");

        Txt_Puesto.setEnabled(false);

        jLabel14.setText("Delta :");

        Txt_Delta.setEnabled(false);

        jLabel15.setText("Cod. Puesto:");

        Txt_CodPuesto.setEnabled(false);

        Txa_Obs.setColumns(20);
        Txa_Obs.setRows(5);
        jScrollPane4.setViewportView(Txa_Obs);

        Cmb_Actividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turno", "Descansa", "Permiso", "Falta", "Vacaciones" }));

        Cmb_Jornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diurna", "Nocturna", "24 Horas" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel13)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Dtm_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(Txt_Cedula)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Txt_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Txt_CodPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_Delta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cmb_Actividad, 0, 146, Short.MAX_VALUE)
                            .addComponent(Cmb_Jornada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dtm_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Txt_Delta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Txt_CodPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Cmb_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Cmb_Jornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tabla_Principal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Cedula", "Nombre", "Apellido", "Puesto", "Delta", "Cod_Puesto", "Actividad", "Jornada", "Obs"
            }
        ));
        Tabla_Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_PrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Principal);

        jLabel11.setText("DESDE :");

        jLabel12.setText("HASTA :");

        Btn_Buscar.setText("Buscar");
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dtm_Desde, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Dtm_Hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Buscar)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Dtm_Desde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Dtm_Hasta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Btn_Buscar))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        Btn_Atras1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Atras1.setText("Atras");
        Btn_Atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Atras1ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Btn_Limpiar.setText("LIMPIAR");
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        Btn_Guardar.setText("GUARDAR");
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setText("ELIMINAR");
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        Btn_Actualizar.setText("ACTUALIZAR");
        Btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Btn_Limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Actualizar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Limpiar)
                    .addComponent(Btn_Guardar)
                    .addComponent(Btn_Eliminar)
                    .addComponent(Btn_Actualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tabla_Empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_Empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_EmpleadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla_Empleado);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("SELECCIONE EMPLEADO");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("SELECCIONE PUESTO");

        Tabla_Puesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_Puesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_PuestoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabla_Puesto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Atras1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Atras1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Atras1ActionPerformed

        Inicio in=new Inicio();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_Atras1ActionPerformed
    private void Limpiar(){
        Dtm_Fecha.setCalendar(null);
        Txt_Cedula.setText("");
        Txt_Nombre.setText("");
        Txt_Apellido.setText("");
        Txt_Puesto.setText("");
        Txt_Delta.setText("");
        Txt_CodPuesto.setText("");
        Cmb_Actividad.setSelectedIndex(0);
        Cmb_Jornada.setSelectedIndex(0);
        Txa_Obs.setText("");
    }
    private boolean Campos_vacios(){
        if(Dtm_Fecha.getDate()!=null&&
            Txt_Cedula.getText().length()!=0&&
            Txt_Nombre.getText().length()!=0&&
            Txt_Apellido.getText().length()!=0&&
            Txt_Puesto.getText().length()!=0&&
            Txt_Delta.getText().length()!=0&&
            Txt_CodPuesto.getText().length()!=0)
        {
            return false;
        }
        else
        {
            return true;
        }
    }
    
    private void MostrarEmpl(){
         try{            
            PreparedStatement ps = con.prepareStatement("select * from Vis_empleado");
            ResultSet rs=ps.executeQuery();
            
            DefaultTableModel modelo=new DefaultTableModel();
            modelo.addColumn("Cedula");
            modelo.addColumn("Apellido 1");
            modelo.addColumn("Nombre");
            modelo.addColumn("Cargo");
            modelo.addColumn("Edad");
            Tabla_Empleado.setModel(modelo);
            String[] dato = new String[5];
            
            while(rs.next()){
                dato[0]=rs.getString("Cedula");
                dato[1]=rs.getString("Apellido1");
                dato[2]=rs.getString("Nombre1");
                dato[3]=rs.getString("Cargo");
                dato[4]=rs.getString("Edad");
                modelo.addRow(dato);
            }
            //Dimensionar tabla
            Tabla_Empleado.getColumnModel().getColumn(0).setPreferredWidth(105);
            Tabla_Empleado.getColumnModel().getColumn(3).setPreferredWidth(100);
            Tabla_Empleado.getColumnModel().getColumn(4).setPreferredWidth(50);
            
        } catch (SQLException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void MostrarPuesto(){
         try{            
            PreparedStatement ps = con.prepareStatement("select * from Vis_puesto");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel modelo=new DefaultTableModel();
            modelo.addColumn("Delta");
            modelo.addColumn("Puesto");
            modelo.addColumn("Telefono");
            modelo.addColumn("Cod_Puesto");
            Tabla_Puesto.setModel(modelo);
            String[] dato = new String[4];
            while(rs.next()){
                dato[0]=rs.getString("N_delta");
                dato[1]=rs.getString("Nombre_puesto");
                dato[2]=rs.getString("Telefono");
                dato[3]=rs.getString("Id_puesto");
                modelo.addRow(dato);
            }
            /*Dimensionar tabla*/
            Tabla_Puesto.getColumnModel().getColumn(0).setPreferredWidth(30);
            
            Tabla_Puesto.getColumnModel().getColumn(3).setPreferredWidth(30);
            
        } catch (SQLException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void MostrarHorario(){
        if(Dtm_Desde.getDate()!=null&& Dtm_Hasta.getDate()!=null){
            java.sql.Date Fecha1 = new java.sql.Date(Dtm_Desde.getDate().getTime());
            java.sql.Date Fecha2 = new java.sql.Date(Dtm_Hasta.getDate().getTime());
            try{
            PreparedStatement ps = con.prepareStatement("call Sp_BuscarHorario(?,?);");
                ps.setDate(1, Fecha1);
                ps.setDate(2, Fecha2);
                ResultSet rs=ps.executeQuery();
                DefaultTableModel modelo=new DefaultTableModel();
                modelo.addColumn("Fecha");
                modelo.addColumn("Cedula");
                modelo.addColumn("Nombre");
                modelo.addColumn("Apellido");
                modelo.addColumn("Puesto");
                modelo.addColumn("Delta");
                modelo.addColumn("Cod_Pues");
                modelo.addColumn("Actividad");
                modelo.addColumn("Jornada");
                modelo.addColumn("Obs");
                Tabla_Principal.setModel(modelo);
                String[] dato = new String[10];
                while(rs.next()){
                    dato[0]=rs.getString("Fecha");
                    dato[1]=rs.getString("Cedula");
                    dato[2]=rs.getString("Nombre1");
                    dato[3]=rs.getString("Apellido1");
                    dato[4]=rs.getString("Nombre_puesto");
                    dato[5]=rs.getString("N_delta");
                    dato[6]=rs.getString("Id_puesto");
                    dato[7]=rs.getString("Actividad");
                    dato[8]=rs.getString("Jornada");
                    dato[9]=rs.getString("Observacion");
                    modelo.addRow(dato);
                }
                //Redimensionar tabla
                Tabla_Principal.getColumnModel().getColumn(0).setPreferredWidth(120);
                Tabla_Principal.getColumnModel().getColumn(2).setPreferredWidth(80);
                Tabla_Principal.getColumnModel().getColumn(3).setPreferredWidth(80);
                Tabla_Principal.getColumnModel().getColumn(4).setPreferredWidth(80);
                Tabla_Principal.getColumnModel().getColumn(5).setPreferredWidth(30);
                Tabla_Principal.getColumnModel().getColumn(6).setPreferredWidth(30);
                Tabla_Principal.getColumnModel().getColumn(9).setPreferredWidth(30);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"ERROR al buscara : "+ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Si desea ver los horarios registrados ingrese fechas para buscar");
        }
    }
    
    private void InsertarHorario(){
        try{
        java.sql.Date Fecha = new java.sql.Date(Dtm_Fecha.getDate().getTime());
        PreparedStatement ps = con.prepareStatement("CALL Sp_InsertarHorario (?,?,?,?,?,?)");
        ps.setDate(1,Fecha);
        ps.setString(2,Txt_Cedula.getText());
        ps.setString(3,Txt_CodPuesto.getText());
        ps.setString(4,Cmb_Actividad.getSelectedItem().toString());
        ps.setString(5,Cmb_Jornada.getSelectedItem().toString());
        ps.setString(6,Txa_Obs.getText());
        int r=ps.executeUpdate();
            if (r>0)
            {
                //JOptionPane.showMessageDialog(null,"Registro guardado");
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Error al registrar datos del Horario");
            }
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"ERROR!! HORARIO : "+ex);
        }
        
    }
    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed

        boolean obj; 
        obj=Campos_vacios();
        if (obj==false){
            java.sql.Date Fecha = new java.sql.Date(Dtm_Fecha.getDate().getTime());//Extrae el YYY-MM-dd
            try{
                PreparedStatement ps = con.prepareStatement("call Sp_VerificarHorario(?,?,?);");
                ps.setDate(1,Fecha);
                ps.setInt(2,Integer.valueOf(Txt_CodPuesto.getText()));
                ps.setString(3,Cmb_Jornada.getSelectedItem().toString());
                ResultSet rs=ps.executeQuery();
                if(rs.next()){//EXISTE EL HORARIO
                    JOptionPane.showMessageDialog(null,"Este horario ya se encuentra registrado");
                }else{//No existe el horario
                    InsertarHorario();
                    JOptionPane.showMessageDialog(null,"Horario registrado correctamente");
                    MostrarHorario();
                }   
            } catch (SQLException ex) {
                Logger.getLogger(Horario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{ 
            JOptionPane.showMessageDialog(null,"Existen campos que estan vacios");
            Txt_Cedula.requestFocus();
        }                
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        // TODO add your handling code here:
         boolean obj; 
        obj=Campos_vacios();
        if (obj==false){//Verificar si los campos no estan vacios
            try{
                java.sql.Date Fecha = new java.sql.Date(Dtm_Fecha.getDate().getTime());//Extrae el YYY-MM-dd
                PreparedStatement ps = con.prepareStatement("CALL Sp_EliminarHorario (?,?,?,?)");
                ps.setDate(1,Fecha);
                ps.setString(2,Txt_Cedula.getText());
                ps.setInt(3,Integer.valueOf(Txt_CodPuesto.getText()));
                ps.setString(4,Cmb_Jornada.getSelectedItem().toString());
                int r=ps.executeUpdate();
                if (r>0)
                {
                    Limpiar();
                    JOptionPane.showMessageDialog(null,"Registro Eliminado");
                    MostrarHorario();
                }
                else
                {
                     JOptionPane.showMessageDialog(null,"No se encontro el registro");
                }
            }catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null,"ERROR!: "+ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Existen campos estan vacios");
            Dtm_Fecha.requestFocus();
        }
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActualizarActionPerformed
        boolean obj; 
        obj=Campos_vacios();
        if (obj==false){//Verificar si los campos no estan vacios
            try{
                java.sql.Date Fecha = new java.sql.Date(Dtm_Fecha.getDate().getTime());//Extrae el YYY-MM-dd
                PreparedStatement ps = con.prepareStatement("CALL Sp_ActualizarHorario (?,?,?,?,?,?)");
                ps.setDate(1,Fecha);
                ps.setString(2,Txt_Cedula.getText());
                ps.setInt(3,Integer.valueOf(Txt_CodPuesto.getText()));
                ps.setString(4,Cmb_Actividad.getSelectedItem().toString());
                ps.setString(5,Cmb_Jornada.getSelectedItem().toString());
                ps.setString(6,Txa_Obs.getText());
                int r=ps.executeUpdate();
                if (r>0)
                {
                    Limpiar();
                    JOptionPane.showMessageDialog(null,"Registro Actualizado");
                    MostrarHorario();
                }
                else
                {
                     JOptionPane.showMessageDialog(null,"No se encontro el registro");
                }
            }catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null,"ERROR!: "+ex);
            }
        }else{
           JOptionPane.showMessageDialog(null,"Existen campos estan vacios");
        }
    }//GEN-LAST:event_Btn_ActualizarActionPerformed

    private void Tabla_EmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_EmpleadoMouseClicked
        // TODO add your handling code here:
        int fila = Tabla_Empleado.rowAtPoint(evt.getPoint());//Obtener la fila donde se selecciona
        
        Txt_Cedula.setText(Tabla_Empleado.getValueAt(fila,0).toString());
        Txt_Apellido.setText(Tabla_Empleado.getValueAt(fila,1).toString());
        Txt_Nombre.setText(Tabla_Empleado.getValueAt(fila,2).toString());
    }//GEN-LAST:event_Tabla_EmpleadoMouseClicked

    private void Tabla_PuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_PuestoMouseClicked
        // TODO add your handling code here:
        int fila = Tabla_Puesto.rowAtPoint(evt.getPoint());//Obtener la fila donde se selecciona
        
        Txt_Delta.setText(Tabla_Puesto.getValueAt(fila,0).toString());
        Txt_Puesto.setText(Tabla_Puesto.getValueAt(fila,1).toString());
        Txt_CodPuesto.setText(Tabla_Puesto.getValueAt(fila,3).toString());
    }//GEN-LAST:event_Tabla_PuestoMouseClicked

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        // PENDIENTE
        MostrarHorario();
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Tabla_PrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_PrincipalMouseClicked
        // TODO add your handling code here:
        try {
        int fila=Tabla_Principal.rowAtPoint(evt.getPoint());
        //Fecha
        SimpleDateFormat FormatoFecha= new SimpleDateFormat("yyyy-MM-dd");
        Dtm_Fecha.setDate(FormatoFecha.parse(Tabla_Principal.getValueAt(fila,0).toString()));
        Txt_Cedula.setText(Tabla_Principal.getValueAt(fila,1).toString());
        Txt_Nombre.setText(Tabla_Principal.getValueAt(fila,2).toString());
        Txt_Apellido.setText(Tabla_Principal.getValueAt(fila,3).toString());
        Txt_Puesto.setText(Tabla_Principal.getValueAt(fila,4).toString());
        Txt_Delta.setText(Tabla_Principal.getValueAt(fila,5).toString());
        Txt_CodPuesto.setText(Tabla_Principal.getValueAt(fila,6).toString());
        //Cmb_Actividad
        for(int i=0; i<=Cmb_Actividad.getItemCount()-1;i++)
        {
            if(Tabla_Principal.getValueAt(fila,7).toString().equals(Cmb_Actividad.getItemAt(i)))
            {
                Cmb_Actividad.setSelectedIndex(i);
            }
        }
        //Cmb_Jornada
        for(int i=0; i<=Cmb_Jornada.getItemCount()-1;i++)
        {
            if(Tabla_Principal.getValueAt(fila,8).toString().equals(Cmb_Jornada.getItemAt(i)))
            {
                Cmb_Jornada.setSelectedIndex(i);
            }
        }
        Txa_Obs.setText(Tabla_Principal.getValueAt(fila,9).toString());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Error : "+ex);
        }
    }//GEN-LAST:event_Tabla_PrincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Horario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar;
    private javax.swing.JButton Btn_Atras1;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JComboBox<String> Cmb_Actividad;
    private javax.swing.JComboBox<String> Cmb_Jornada;
    private com.toedter.calendar.JDateChooser Dtm_Desde;
    private com.toedter.calendar.JDateChooser Dtm_Fecha;
    private com.toedter.calendar.JDateChooser Dtm_Hasta;
    private javax.swing.JTable Tabla_Empleado;
    private javax.swing.JTable Tabla_Principal;
    private javax.swing.JTable Tabla_Puesto;
    private javax.swing.JTextArea Txa_Obs;
    private javax.swing.JTextField Txt_Apellido;
    private javax.swing.JTextField Txt_Cedula;
    private javax.swing.JTextField Txt_CodPuesto;
    private javax.swing.JTextField Txt_Delta;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_Puesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
